import { GESTURES } from './gestures.js'
import { COMMANDS } from './commands.js'

export const DEFAULT_GESTURE_MAP = {
  [GESTURES.HEAD_UP]: COMMANDS.VOL_UP,
  [GESTURES.HEAD_DOWN]: COMMANDS.VOL_DOWN,
  [GESTURES.HEAD_LEFT]: COMMANDS.REWIND,
  [GESTURES.HEAD_RIGHT]: COMMANDS.NEXT,
  [GESTURES.EYES_CLOSED]: COMMANDS.PAUSE,
  [GESTURES.MOUTH_OPEN]: COMMANDS.MUTE,
  [GESTURES.TILT_LEFT]: COMMANDS.REWIND,
  [GESTURES.TILT_RIGHT]: COMMANDS.SKIP,
}

export const DEFAULT_COOLDOWNS = {
  [GESTURES.HEAD_UP]: 1500,
  [GESTURES.HEAD_DOWN]: 1500,
  [GESTURES.HEAD_LEFT]: 1500,
  [GESTURES.HEAD_RIGHT]: 1500,
  [GESTURES.EYES_CLOSED]: 1200,
  [GESTURES.MOUTH_OPEN]: 1200,
  [GESTURES.TILT_LEFT]: 1500,
  [GESTURES.TILT_RIGHT]: 1500,
}

export const SENSITIVITY_LABELS = {
  low: 'Low (Less sensitive)',
  medium: 'Medium (Default)',
  high: 'High (More sensitive)',
}
